services:
  storage:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: "@Password123!"
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console port
    volumes:
      - storage:/data
    networks:
      - go_networks

  networks:
    go_networks:
      driver: bridge